### PR TITLE
Feature/pk chunking

### PR DESCRIPTION
**Pull request by ronnievisser**
Add option to run batch with PKChunking enabled.

### CODE REVIEW

**Comment by frankkessler** [comment]
#53

**Comment by frankkessler** [comment]
Thanks @ronnievisser .  I checked out this request.  The only thing I would change is where you injest the header.  I would keep that bulk client clean and add this special header to the requests that need it.  You can add an option to the runBatch function for the pksize initialized to null.  If you set it to a number, the pksize should be checked later on how to handle the batch response.  You might be able to use the code that runs when "isBatchedResult" is set as an option as well.

I might be able to help with some of this next week.

**Comment by ronnievisser** [comment]
Ok! that would be great! I will also take a good look at it to optimize.

**Comment by ronnievisser** [comment]
Hi @frankkessler,

do you have any ETa on when you could review this? I actually need it working on wednesday. It would be very helpful if you could help with your ideas or merge this.

thanks

**Comment by frankkessler** [comment]
Added in version v0.4.14

**Comment by ronnievisser** [comment]
Hi @frankkessler,

Maybe I'm looking incorrectly but I have the feeling this doesn't help. you are still putting the result of all the batches in the $batches array. this would still cause memory issues. the difference with my change was the callback function that processes each batch result separately.

**Comment by frankkessler** [comment]
@ronnievisser Hey, I missed the callable in your implementation.  I just added in the ability to supply a class that will process all of the records and skip adding the records to the normal batch response.  I hope that helps.

**Pull request closed without merging**
